### ISSUE TITLE
Spell check. 

### ISSUE THREAD

**Issue by simar1998** [Kemp-SUAS/FalloutTNG#4]
Hello faduma could you keep my readme always free of grammatical errors and spell check it for me.  I would put Kieran in charge but I got higher marks than him on a essay I wrote titled the blue hose. Which was as the name suggested about a blue hose.  So clearly he is doing something wrong.

**Comment by Faduma-Ahmed** [comment]
Fallout The New Generation, where no vault boy has gone before.

This program is a fan re-creation of the 19 year old game Fallout, with some unique changes. Our take on this universally acclaimed and action packed game will feature lore-friendly content that will bring excitement to any player. The rich dialog options will create dynamic game play will allow players to have a continuous interest in this game as it progresses. Extensive amounts of lore will allow any true gaming fan to follow the story of a vault dweller through out his journey to a post-apocalyptic world. This game features customizable character creation allowing the player to journey through the world as if it was themselves. This school project encourages us  to recreate games that we grew up with while testing our skills of programming and working as a team. Our UML diagram and design document can be seen below.
- This is my updated version But all in all ... It was good !

**Comment by simar1998** [comment]
Could you please look at the to-do list that is just awfull.
